exp: MinimalPair

mode: 
    - evaluate

models: 
      hf_masked_model:
          - bert-base-cased

datafpath: Midterm_Replication/rep-tse/data/obj_rel_no_that_small.tsv
predfpath: Midterm_Replication/rep-tse/bert_cased_evaluation/obj_rel_no_that_small_evaluation_bert.tsv

batchSize: 512
